extern const GeoLayout boombox_geo[];
extern Lights1 boombox_f3dlite_material_003_lights;
extern Lights1 boombox_f3dlite_material_004_lights;
extern Vtx boombox_Bone_mesh_layer_1_vtx_0[92];
extern Gfx boombox_Bone_mesh_layer_1_tri_0[];
extern Vtx boombox_Bone_mesh_layer_1_vtx_1[128];
extern Gfx boombox_Bone_mesh_layer_1_tri_1[];
extern Gfx mat_boombox_f3dlite_material_003[];
extern Gfx mat_boombox_f3dlite_material_004[];
extern Gfx boombox_Bone_mesh_layer_1[];
extern Gfx boombox_material_revert_render_settings[];
